version: "3"

services: 
    node_api_1:
        build: containers/node/
        command: npm start
        ports:
            - "443:3000"
            - "80:3000"
            - "9229:9229" #debug port
        volumes:
            - .containers/node/:/usr/app
        networks:
            - adnois
    nginx:
        image: nginx:stable-alpine
        ports:
            - 3001:80
        depends_on:
            - node_api_1
        volumes:
            - ./containers/nginx/nginx.conf:/etc/adonis/nginx/conf.d/default.conf:ro
            - ./containers/nginx:/var/log/adonis/nginx
        networks:
            - adnois
networks: 
    adnois:
        driver: bridge
        
